-- Replace the password hash with one generated by:
-- php -r "echo password_hash('CHANGE_THIS_PASSWORD', PASSWORD_DEFAULT), PHP_EOL;"
INSERT INTO admin_users (username, password_hash)
VALUES ('admin', '$2y$10$REPLACE_THIS_WITH_A_REAL_PASSWORD_HASH');
